// ============ PRODUCTS DATA ============
export const PRODUCTS = [
  {
    id: 1,
    name: "Lenovo LOQ 15 AMD Ryzen 5 7235HS / 16GB / 512GB / RTX 4050",
    slug: "lenovo-loq-15-ryzen5-7235hs-rtx4050",
    brand: "Lenovo",
    series: "LOQ",
    sku: "LNV-LOQ15-R5-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 349990,
    oldPrice: 389990,
    discountPercent: 10,
    saving: 40000,
    monthlyPayment: 29166,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: true,
    isSale: true,
    rating: 4.8,
    reviewCount: 247,
    color: "Storm Grey",
    weight: "2.4 кг",
    // specs
    processor: "AMD Ryzen 5 7235HS",
    processorBrand: "AMD",
    gpu: "NVIDIA GeForce RTX 4050 6GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "512 ГБ NVMe SSD",
    display: "15.6\"",
    resolution: "1920×1080",
    refreshRate: "144 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "60 Вт·ч",
    wifi: "Wi-Fi 6 (802.11ax)",
    bluetooth: "Bluetooth 5.1",
    camera: "720p HD",
    dimensions: "359.1 × 256 × 23.9 мм",
    ports: "USB-A 3.2 Gen1 × 2, USB-A 2.0, USB-C 3.2, HDMI 2.1, RJ-45, 3.5mm аудио",
    shortDescription: "Доступный игровой ноутбук с RTX 4050 для требовательных игр и контента",
    description: "Lenovo LOQ 15 — отличный выбор для геймеров, ищущих мощный ноутбук по разумной цене. AMD Ryzen 5 7235HS обеспечивает плавную работу в большинстве современных игр, а RTX 4050 позволяет наслаждаться играми с высокими настройками графики при 144 Гц.",
    advantages: [
      "Дискретная видеокарта RTX 4050 для игр",
      "144 Гц IPS-дисплей без мерцания",
      "16 ГБ DDR5 для многозадачности",
      "Быстрый NVMe SSD Gen4",
      "Продвинутая система охлаждения",
      "Wi-Fi 6 для стабильного соединения",
      "Windows 11 в комплекте",
      "Металлический корпус"
    ],
    bgGradient: "linear-gradient(150deg,#F1E9FB,#EAE1F9)",
    svgColor1: "#5b2a86",
    svgColor2: "#ff5a1f",
    images: ["/laptops/lenovo-loq-15.svg"],
  },
  {
    id: 2,
    name: "Lenovo LOQ 17 Intel Core i5-13450HX / 12GB / 512GB / RTX",
    slug: "lenovo-loq-17-i5-13450hx",
    brand: "Lenovo",
    series: "LOQ",
    sku: "LNV-LOQ17-I5-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 419990,
    oldPrice: 469990,
    discountPercent: 11,
    saving: 50000,
    monthlyPayment: 34999,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: false,
    isSale: true,
    rating: 4.7,
    reviewCount: 183,
    color: "Storm Grey",
    weight: "2.9 кг",
    processor: "Intel Core i5-13450HX",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 4050 6GB",
    gpuBrand: "NVIDIA",
    ram: "12 ГБ DDR5",
    storage: "512 ГБ NVMe SSD",
    display: "17.3\"",
    resolution: "1920×1080",
    refreshRate: "144 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "60 Вт·ч",
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.1",
    camera: "720p HD",
    dimensions: "398.4 × 279.1 × 25.6 мм",
    ports: "USB-A 3.2 Gen1 × 2, USB-A 2.0, USB-C 3.2, HDMI 2.1, RJ-45",
    shortDescription: "Большой 17.3\" игровой ноутбук с мощным Intel Core i5 HX",
    description: "Lenovo LOQ 17 предлагает большой экран для комфортного гейминга с Intel Core i5-13450HX на борту.",
    advantages: ["17.3\" дисплей 144 Гц","Intel Core i5-13450HX","RTX 4050 для требовательных игр","Большой аккумулятор","Быстрый SSD","Wi-Fi 6","Windows 11","Мощное охлаждение"],
    bgGradient: "linear-gradient(150deg,#E8F1FB,#DDE8F9)",
    svgColor1: "#2a5286",
    svgColor2: "#1f5ab8",
    images: [],
  },
  {
    id: 3,
    name: "Lenovo Legion 5 Intel Core Ultra 7 255HX / 16GB / 512GB / RTX 5060",
    slug: "lenovo-legion-5-ultra7-rtx5060",
    brand: "Lenovo",
    series: "Legion 5",
    sku: "LNV-LEG5-CU7-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 699990,
    oldPrice: 779990,
    discountPercent: 10,
    saving: 80000,
    monthlyPayment: 58332,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: true,
    isSale: false,
    rating: 4.9,
    reviewCount: 412,
    color: "Titanium Grey",
    weight: "2.4 кг",
    processor: "Intel Core Ultra 7 255HX",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 5060 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "512 ГБ NVMe SSD Gen4",
    display: "15.6\"",
    resolution: "1920×1080",
    refreshRate: "165 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "80 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "357 × 263.8 × 21.7 мм",
    ports: "USB-A 3.2 × 3, USB-C 3.2 Thunderbolt 4, HDMI 2.1, RJ-45, SD Card",
    shortDescription: "Флагманский игровой ноутбук нового поколения с RTX 5060",
    description: "Lenovo Legion 5 с Intel Core Ultra 7 255HX и RTX 5060 — это максимальная производительность для профессиональных геймеров 2025 года.",
    advantages: ["RTX 5060 нового поколения","Intel Core Ultra 7 255HX","165 Гц IPS-дисплей","Thunderbolt 4","Wi-Fi 6E","80 Вт·ч батарея","Система охлаждения Legion Coldfront","RGB-подсветка клавиатуры"],
    bgGradient: "linear-gradient(150deg,#EBF1FF,#DDE5FF)",
    svgColor1: "#1a2f80",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 4,
    name: "Lenovo Legion Pro 5 AMD Ryzen 9 9955HX / 32GB / 2TB",
    slug: "lenovo-legion-pro-5-r9-9955hx",
    brand: "Lenovo",
    series: "Legion Pro 5",
    sku: "LNV-LEGP5-R9-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 899990,
    oldPrice: 999990,
    discountPercent: 10,
    saving: 100000,
    monthlyPayment: 74999,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 5.0,
    reviewCount: 98,
    color: "Onyx Grey",
    weight: "2.5 кг",
    processor: "AMD Ryzen 9 9955HX",
    processorBrand: "AMD",
    gpu: "NVIDIA GeForce RTX 5070 Ti 12GB",
    gpuBrand: "NVIDIA",
    ram: "32 ГБ DDR5",
    storage: "2 ТБ NVMe SSD",
    display: "16\"",
    resolution: "2560×1600",
    refreshRate: "240 Гц",
    matrixType: "IPS",
    warranty: "2 года",
    os: "Windows 11 Home",
    battery: "99.9 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "360 × 264 × 22.4 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4 × 2, HDMI 2.1, RJ-45",
    shortDescription: "Профессиональный игровой ноутбук с AMD Ryzen 9 и 32 ГБ RAM",
    description: "Legion Pro 5 с Ryzen 9 9955HX — для тех, кто не хочет идти на компромисс. 32 ГБ DDR5, 2 ТБ SSD и RTX 5070 Ti.",
    advantages: ["AMD Ryzen 9 9955HX — топ производительности","32 ГБ DDR5 памяти","2 ТБ NVMe SSD","240 Гц 2K дисплей","RTX 5070 Ti","99.9 Вт·ч батарея","Thunderbolt 4 × 2","Гарантия 2 года"],
    bgGradient: "linear-gradient(150deg,#F0EBF9,#E8DFF7)",
    svgColor1: "#3a1a6e",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 5,
    name: "HP Omen 16 Intel Core Ultra 7 255H / 16GB / 1TB / RTX 5060",
    slug: "hp-omen-16-ultra7-rtx5060",
    brand: "HP",
    series: "OMEN 16",
    sku: "HP-OMN16-CU7-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 749990,
    oldPrice: 829990,
    discountPercent: 10,
    saving: 80000,
    monthlyPayment: 62499,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: true,
    isSale: false,
    rating: 4.8,
    reviewCount: 156,
    color: "Shadow Black",
    weight: "2.45 кг",
    processor: "Intel Core Ultra 7 255H",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 5060 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "1 ТБ NVMe SSD",
    display: "16.1\"",
    resolution: "1920×1080",
    refreshRate: "165 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "83 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "720p HD",
    dimensions: "358 × 270 × 23.9 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4, HDMI 2.1, RJ-45, MicroSD",
    shortDescription: "Игровой флагман HP с Intel Core Ultra 7 и RTX 5060",
    description: "HP Omen 16 — профессиональный игровой ноутбук для заядлых геймеров и контент-мейкеров.",
    advantages: ["Intel Core Ultra 7 255H","RTX 5060 8GB GDDR7","165 Гц IPS","Thunderbolt 4","Wi-Fi 6E","OMEN Command Center","RGB клавиатура","Мощное охлаждение"],
    bgGradient: "linear-gradient(150deg,#F5EBF5,#F0DFF0)",
    svgColor1: "#4a0e6e",
    svgColor2: "#1a1a2e",
    images: [],
  },
  {
    id: 6,
    name: "HP Victus 15 Intel Core i7-13620H / 16GB / 512GB / RTX 5060",
    slug: "hp-victus-15-i7-13620h-rtx5060",
    brand: "HP",
    series: "Victus 15",
    sku: "HP-VIC15-I7-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 469990,
    oldPrice: 519990,
    discountPercent: 10,
    saving: 50000,
    monthlyPayment: 39166,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: true,
    isSale: true,
    rating: 4.7,
    reviewCount: 321,
    color: "Mica Silver",
    weight: "2.37 кг",
    processor: "Intel Core i7-13620H",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 5060 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR4",
    storage: "512 ГБ NVMe SSD",
    display: "15.6\"",
    resolution: "1920×1080",
    refreshRate: "144 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "70.9 Вт·ч",
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.3",
    camera: "720p HD",
    dimensions: "359.4 × 253.4 × 22.8 мм",
    ports: "USB-A 3.2 × 3, USB-C 3.2, HDMI 2.1, RJ-45",
    shortDescription: "Доступный игровой ноутбук HP с i7 и RTX 5060",
    description: "HP Victus 15 — отличное соотношение цены и мощности для современных игр.",
    advantages: ["RTX 5060 8GB за разумную цену","i7-13620H 10 ядер","144 Гц IPS","Просторный 15.6\" экран","Быстрый SSD","Wi-Fi 6","Стильный дизайн","Windows 11"],
    bgGradient: "linear-gradient(150deg,#EBF5F5,#DFF0F0)",
    svgColor1: "#0e4e6e",
    svgColor2: "#0077b6",
    images: [],
  },
  {
    id: 7,
    name: "ASUS ROG Strix G16 AMD Ryzen 9 8940HX / 16GB / 1TB / RTX 5070",
    slug: "asus-rog-strix-g16-r9-rtx5070",
    brand: "ASUS",
    series: "ROG Strix G16",
    sku: "ASUS-ROG-G16-R9-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 899990,
    oldPrice: 999990,
    discountPercent: 10,
    saving: 100000,
    monthlyPayment: 74999,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: true,
    isSale: false,
    rating: 5.0,
    reviewCount: 524,
    color: "Eclipse Gray",
    weight: "2.5 кг",
    processor: "AMD Ryzen 9 8940HX",
    processorBrand: "AMD",
    gpu: "NVIDIA GeForce RTX 5070 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "1 ТБ NVMe SSD Gen4",
    display: "16\"",
    resolution: "2560×1600",
    refreshRate: "240 Гц",
    matrixType: "IPS",
    warranty: "2 года",
    os: "Windows 11 Home",
    battery: "90 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "354 × 259 × 27.2 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4, HDMI 2.1, RJ-45, SD Card",
    shortDescription: "Флагманский ROG с Ryzen 9 и RTX 5070 для максимального гейминга",
    description: "ASUS ROG Strix G16 — топовый игровой ноутбук с передовой системой охлаждения ROG.",
    advantages: ["AMD Ryzen 9 8940HX","RTX 5070 8GB GDDR7","240 Гц 2K QHD+","Thunderbolt 4","Wi-Fi 6E","Per-key RGB клавиатура","ROG Armoury Crate","Гарантия 2 года"],
    bgGradient: "linear-gradient(150deg,#EBEAF9,#DDDCF5)",
    svgColor1: "#2a2870",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 8,
    name: "ASUS TUF Gaming F16 Intel Core i5-210H / 16GB / 512GB / RTX 3050",
    slug: "asus-tuf-f16-i5-rtx3050",
    brand: "ASUS",
    series: "TUF Gaming F16",
    sku: "ASUS-TUF-F16-I5-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 329990,
    oldPrice: 369990,
    discountPercent: 11,
    saving: 40000,
    monthlyPayment: 27499,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: true,
    isSale: true,
    rating: 4.6,
    reviewCount: 398,
    color: "Mecha Gray",
    weight: "2.2 кг",
    processor: "Intel Core i5-210H",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 3050 6GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "512 ГБ NVMe SSD",
    display: "16\"",
    resolution: "1920×1200",
    refreshRate: "165 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "90 Вт·ч",
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.3",
    camera: "720p HD",
    dimensions: "356.8 × 255.6 × 24.9 мм",
    ports: "USB-A 3.2 × 3, USB-C 3.2, HDMI 2.0, RJ-45",
    shortDescription: "Надёжный игровой ноутбук ASUS TUF с военным стандартом прочности",
    description: "ASUS TUF Gaming F16 прошёл военные испытания MIL-STD-810H и предлагает максимальную надёжность.",
    advantages: ["MIL-STD-810H прочность","RTX 3050 для игр","165 Гц 16\" дисплей","Большая батарея 90 Вт·ч","Продвинутое охлаждение","RGB клавиатура","Надёжный SSD","Wi-Fi 6"],
    bgGradient: "linear-gradient(150deg,#EBF5EE,#DFF0E4)",
    svgColor1: "#1a6e2e",
    svgColor2: "#0d4d1e",
    images: [],
  },
  {
    id: 9,
    name: "ASUS TUF Gaming A16 FA608P AMD Ryzen 9 8940HX / 16GB / 1TB",
    slug: "asus-tuf-a16-r9-8940hx",
    brand: "ASUS",
    series: "TUF Gaming A16",
    sku: "ASUS-TUF-A16-R9-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 649990,
    oldPrice: 729990,
    discountPercent: 11,
    saving: 80000,
    monthlyPayment: 54166,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 4.8,
    reviewCount: 187,
    color: "Graphite Black",
    weight: "2.5 кг",
    processor: "AMD Ryzen 9 8940HX",
    processorBrand: "AMD",
    gpu: "AMD Radeon RX 7600M XT 8GB",
    gpuBrand: "AMD",
    ram: "16 ГБ DDR5",
    storage: "1 ТБ NVMe SSD",
    display: "16\"",
    resolution: "1920×1200",
    refreshRate: "165 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "90 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "720p HD",
    dimensions: "357 × 257 × 26.6 мм",
    ports: "USB-A 3.2 × 3, USB-C 3.2, HDMI 2.1, RJ-45",
    shortDescription: "Мощный ASUS TUF A16 с AMD Ryzen 9 и Radeon RX 7600M XT",
    description: "ASUS TUF Gaming A16 с топовым AMD Ryzen 9 8940HX — для игр и творческих задач.",
    advantages: ["AMD Ryzen 9 8940HX","Radeon RX 7600M XT 8GB","165 Гц 16\" FHD+","MIL-STD-810H","90 Вт·ч батарея","Wi-Fi 6E","Mux Switch","Продвинутое охлаждение"],
    bgGradient: "linear-gradient(150deg,#F5EBF0,#F0DFE8)",
    svgColor1: "#6e1a2e",
    svgColor2: "#e0002b",
    images: [],
  },
  {
    id: 10,
    name: "Acer Predator Helios Neo 16S AI Intel Core Ultra 9-275HX / 32GB",
    slug: "acer-predator-helios-neo-16s-ultra9",
    brand: "Acer",
    series: "Predator Helios Neo 16S",
    sku: "ACER-PHN16S-CU9-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 1099990,
    oldPrice: 1249990,
    discountPercent: 12,
    saving: 150000,
    monthlyPayment: 91666,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 4.9,
    reviewCount: 64,
    color: "Abyssal Black",
    weight: "3.0 кг",
    processor: "Intel Core Ultra 9-275HX",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 5080 16GB",
    gpuBrand: "NVIDIA",
    ram: "32 ГБ DDR5",
    storage: "2 ТБ NVMe SSD Gen5",
    display: "16\"",
    resolution: "2560×1600",
    refreshRate: "240 Гц",
    matrixType: "Mini-LED",
    warranty: "2 года",
    os: "Windows 11 Home",
    battery: "99.9 Вт·ч",
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 5.4",
    camera: "1080p FHD",
    dimensions: "367 × 282 × 24.9 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4 × 2, HDMI 2.1, RJ-45, SD",
    shortDescription: "Ультимативный игровой ноутбук с RTX 5080 и Mini-LED",
    description: "Acer Predator Helios Neo 16S AI — флагман среди игровых ноутбуков 2025 года с RTX 5080 и Wi-Fi 7.",
    advantages: ["Intel Core Ultra 9-275HX","RTX 5080 16GB GDDR7","240 Гц Mini-LED 2K","Wi-Fi 7","Thunderbolt 4 × 2","32 ГБ DDR5","2 ТБ Gen5 SSD","Гарантия 2 года"],
    bgGradient: "linear-gradient(150deg,#F5EBEB,#F0DFDF)",
    svgColor1: "#6e1a1a",
    svgColor2: "#e00000",
    images: [],
  },
  {
    id: 11,
    name: "HP Laptop 15 AMD Ryzen 5 7520U / 8GB / 512GB",
    slug: "hp-laptop-15-ryzen5-7520u",
    brand: "HP",
    series: "Laptop 15",
    sku: "HP-LAP15-R5-001",
    categorySlug: "office",
    categoryName: "Для работы",
    price: 219990,
    oldPrice: 249990,
    discountPercent: 12,
    saving: 30000,
    monthlyPayment: 18332,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: true,
    isSale: true,
    rating: 4.5,
    reviewCount: 567,
    color: "Natural Silver",
    weight: "1.75 кг",
    processor: "AMD Ryzen 5 7520U",
    processorBrand: "AMD",
    gpu: "AMD Radeon 610M",
    gpuBrand: "AMD",
    ram: "8 ГБ DDR5",
    storage: "512 ГБ NVMe SSD",
    display: "15.6\"",
    resolution: "1920×1080",
    refreshRate: "60 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "41 Вт·ч",
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.3",
    camera: "720p HD",
    dimensions: "357.5 × 231.5 × 19.9 мм",
    ports: "USB-A 3.0 × 2, USB-A 2.0, USB-C 3.2, HDMI 1.4, RJ-45",
    shortDescription: "Доступный ноутбук для офиса и учёбы на AMD Ryzen 5",
    description: "HP Laptop 15 — надёжный и доступный ноутбук для ежедневной работы, учёбы и интернет-сёрфинга.",
    advantages: ["Тонкий и лёгкий корпус","AMD Ryzen 5 7520U","Быстрый NVMe SSD","IPS Full HD экран","Wi-Fi 6","Windows 11","Долгое время работы","Доступная цена"],
    bgGradient: "linear-gradient(150deg,#EBF0F5,#DFE8F0)",
    svgColor1: "#1a4e6e",
    svgColor2: "#0077b6",
    images: [],
  },
  {
    id: 12,
    name: "HP OmniBook 5 Qualcomm Snapdragon X Plus / 32GB / 512GB / 16\"",
    slug: "hp-omnibook-5-snapdragon-x-plus",
    brand: "HP",
    series: "OmniBook 5",
    sku: "HP-OMB5-SNAP-001",
    categorySlug: "ultrabook",
    categoryName: "Ультрабуки",
    price: 499990,
    oldPrice: 549990,
    discountPercent: 9,
    saving: 50000,
    monthlyPayment: 41666,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 4.7,
    reviewCount: 89,
    color: "Meteor Silver",
    weight: "1.58 кг",
    processor: "Qualcomm Snapdragon X Plus X1P-42-100",
    processorBrand: "Qualcomm",
    gpu: "Qualcomm Adreno",
    gpuBrand: "Qualcomm",
    ram: "32 ГБ LPDDR5x",
    storage: "512 ГБ NVMe SSD",
    display: "16\"",
    resolution: "1920×1200",
    refreshRate: "60 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "59 Вт·ч",
    wifi: "Wi-Fi 7",
    bluetooth: "Bluetooth 5.4",
    camera: "5MP FHD",
    dimensions: "354.8 × 247.4 × 16.9 мм",
    ports: "USB-C × 3, USB-A 3.2, HDMI 2.1, Nano SIM",
    shortDescription: "Тонкий ультрабук на ARM с Wi-Fi 7 и 32 ГБ памяти",
    description: "HP OmniBook 5 на базе Snapdragon X Plus — лёгкий и мощный ноутбук для мобильных профессионалов.",
    advantages: ["Snapdragon X Plus ARM","32 ГБ LPDDR5x","Wi-Fi 7","Тонкий корпус 16.9 мм","Долгая автономность","5 МП камера","3 × USB-C","Быстрая зарядка"],
    bgGradient: "linear-gradient(150deg,#F5F5EB,#F0F0DF)",
    svgColor1: "#4e6e1a",
    svgColor2: "#0077b6",
    images: [],
  },
  {
    id: 13,
    name: "Lenovo ThinkPad X9 Aura Edition Gen 1 Intel Core Ultra 5 226V",
    slug: "lenovo-thinkpad-x9-aura-gen1",
    brand: "Lenovo",
    series: "ThinkPad X9",
    sku: "LNV-TPX9-CU5-001",
    categorySlug: "ultrabook",
    categoryName: "Ультрабуки",
    price: 599990,
    oldPrice: 669990,
    discountPercent: 10,
    saving: 70000,
    monthlyPayment: 49999,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 4.9,
    reviewCount: 43,
    color: "Crystal Blue",
    weight: "1.12 кг",
    processor: "Intel Core Ultra 5 226V",
    processorBrand: "Intel",
    gpu: "Intel Arc Graphics",
    gpuBrand: "Intel",
    ram: "32 ГБ LPDDR5x",
    storage: "512 ГБ NVMe SSD",
    display: "14\"",
    resolution: "2880×1800",
    refreshRate: "120 Гц",
    matrixType: "OLED",
    warranty: "1 год",
    os: "Windows 11 Pro",
    battery: "55 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "313.7 × 217.4 × 13.2 мм",
    ports: "USB-C Thunderbolt 4 × 2, USB-A 3.2",
    shortDescription: "Ультратонкий бизнес-ноутбук с OLED 2.8K и весом 1.12 кг",
    description: "ThinkPad X9 Aura Edition — самый тонкий и лёгкий ThinkPad с OLED-экраном 2.8K.",
    advantages: ["Вес всего 1.12 кг","OLED 2.8K 120 Гц","Intel Core Ultra 5 226V","32 ГБ LPDDR5x","Thunderbolt 4 × 2","Windows 11 Pro","Ультратонкий 13.2 мм","Долгая автономность"],
    bgGradient: "linear-gradient(150deg,#EBF0F5,#DFE8F0)",
    svgColor1: "#1a2e6e",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 14,
    name: "Lenovo IdeaPad Slim 3 AMD Ryzen 7 5825U",
    slug: "lenovo-ideapad-slim3-r7-5825u",
    brand: "Lenovo",
    series: "IdeaPad Slim 3",
    sku: "LNV-IPS3-R7-001",
    categorySlug: "office",
    categoryName: "Для работы",
    price: 269990,
    oldPrice: 299990,
    discountPercent: 10,
    saving: 30000,
    monthlyPayment: 22499,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: true,
    isSale: true,
    rating: 4.6,
    reviewCount: 412,
    color: "Arctic Grey",
    weight: "1.4 кг",
    processor: "AMD Ryzen 7 5825U",
    processorBrand: "AMD",
    gpu: "AMD Radeon Graphics",
    gpuBrand: "AMD",
    ram: "8 ГБ DDR4",
    storage: "512 ГБ NVMe SSD",
    display: "15.6\"",
    resolution: "1920×1080",
    refreshRate: "60 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "45 Вт·ч",
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.1",
    camera: "720p HD",
    dimensions: "359 × 233.6 × 17.9 мм",
    ports: "USB-A 3.2, USB-A 2.0, USB-C 3.2, HDMI 1.4, SD Card",
    shortDescription: "Тонкий и доступный ноутбук для работы и учёбы",
    description: "IdeaPad Slim 3 с AMD Ryzen 7 — идеальный выбор для студентов и офисных работников.",
    advantages: ["Тонкий корпус 17.9 мм","AMD Ryzen 7 5825U","Хорошая автономность","SD Card Reader","Wi-Fi 6","Быстрый SSD","Доступная цена","Лёгкий 1.4 кг"],
    bgGradient: "linear-gradient(150deg,#EBF5F0,#DFF0E8)",
    svgColor1: "#1a6e4e",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 15,
    name: "Dell Vostro 3530 Intel Core i5-1235U / Intel Iris Xe Graphics",
    slug: "dell-vostro-3530-i5-1235u",
    brand: "Dell",
    series: "Vostro 3530",
    sku: "DELL-VST3530-I5-001",
    categorySlug: "office",
    categoryName: "Для работы",
    price: 249990,
    oldPrice: 279990,
    discountPercent: 11,
    saving: 30000,
    monthlyPayment: 20832,
    inStock: true,
    stockStatus: "in_stock",
    isNew: false,
    isHit: false,
    isSale: true,
    rating: 4.4,
    reviewCount: 234,
    color: "Carbon Black",
    weight: "1.83 кг",
    processor: "Intel Core i5-1235U",
    processorBrand: "Intel",
    gpu: "Intel Iris Xe Graphics",
    gpuBrand: "Intel",
    ram: "8 ГБ DDR4",
    storage: "512 ГБ NVMe SSD",
    display: "15.6\"",
    resolution: "1920×1080",
    refreshRate: "60 Гц",
    matrixType: "WVA",
    warranty: "1 год",
    os: "Windows 11 Pro",
    battery: "41 Вт·ч",
    wifi: "Wi-Fi 6",
    bluetooth: "Bluetooth 5.0",
    camera: "720p HD",
    dimensions: "358.9 × 232.6 × 18.9 мм",
    ports: "USB-A 3.2 × 2, USB-A 2.0, USB-C 3.2, HDMI 1.4, RJ-45, SD Card",
    shortDescription: "Бизнес-ноутбук Dell с Windows 11 Pro для офиса",
    description: "Dell Vostro 3530 — надёжный бизнес-ноутбук с Windows 11 Pro и хорошей автономностью.",
    advantages: ["Windows 11 Pro","Intel i5-1235U","Надёжный корпус Dell","SD Card Reader","Wi-Fi 6","RJ-45 Ethernet","Быстрый SSD","Бизнес-сертификация"],
    bgGradient: "linear-gradient(150deg,#EBF0F5,#DFE4F0)",
    svgColor1: "#1a3a6e",
    svgColor2: "#007db8",
    images: [],
  },
  {
    id: 16,
    name: "ASUS TUF Gaming F16 FX608L Intel Core Ultra 5 235HX / 16GB",
    slug: "asus-tuf-f16-fx608l-ultra5",
    brand: "ASUS",
    series: "TUF Gaming F16",
    sku: "ASUS-TUF-F16-CU5-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 549990,
    oldPrice: 619990,
    discountPercent: 11,
    saving: 70000,
    monthlyPayment: 45832,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 4.8,
    reviewCount: 127,
    color: "Mecha Gray",
    weight: "2.2 кг",
    processor: "Intel Core Ultra 5 235HX",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 4060 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "1 ТБ NVMe SSD",
    display: "16\"",
    resolution: "1920×1200",
    refreshRate: "165 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "90 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "720p HD",
    dimensions: "357 × 257 × 24.9 мм",
    ports: "USB-A 3.2 × 3, USB-C 3.2, HDMI 2.1, RJ-45",
    shortDescription: "Новейший ASUS TUF с Core Ultra 5 и RTX 4060",
    description: "ASUS TUF Gaming F16 FX608L с Intel Core Ultra 5 235HX — современный игровой ноутбук с надёжностью TUF.",
    advantages: ["Intel Core Ultra 5 235HX","RTX 4060 8GB","165 Гц FHD+","MIL-STD-810H","90 Вт·ч батарея","Wi-Fi 6E","RGB клавиатура","Надёжное охлаждение"],
    bgGradient: "linear-gradient(150deg,#EBF5EE,#DFF0E4)",
    svgColor1: "#1a6e2e",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 17,
    name: "Lenovo Legion Pro 5 Intel Core i7-14650HX / 16GB / 1TB / RTX 5060",
    slug: "lenovo-legion-pro-5-i7-14650hx-rtx5060",
    brand: "Lenovo",
    series: "Legion Pro 5",
    sku: "LNV-LEGP5-I7-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 749990,
    oldPrice: 839990,
    discountPercent: 11,
    saving: 90000,
    monthlyPayment: 62499,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: true,
    isSale: false,
    rating: 4.9,
    reviewCount: 203,
    color: "Onyx Grey",
    weight: "2.5 кг",
    processor: "Intel Core i7-14650HX",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 5060 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "1 ТБ NVMe SSD",
    display: "16\"",
    resolution: "2560×1600",
    refreshRate: "240 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "99.9 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "360 × 264 × 22.4 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4 × 2, HDMI 2.1, RJ-45",
    shortDescription: "Игровой флагман Legion Pro 5 с i7 и RTX 5060",
    description: "Lenovo Legion Pro 5 с Core i7-14650HX и RTX 5060 — мощный выбор для требовательных игр.",
    advantages: ["Intel Core i7-14650HX","RTX 5060 8GB","240 Гц 2K","Thunderbolt 4 × 2","99.9 Вт·ч","Wi-Fi 6E","1080p камера","Legion AI Engine"],
    bgGradient: "linear-gradient(150deg,#EBF0F5,#DFE8F0)",
    svgColor1: "#1a2e6e",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 18,
    name: "Lenovo Legion Pro 5 AMD Ryzen 7 8745HX / 32GB / 1TB / RTX 5060",
    slug: "lenovo-legion-pro-5-r7-8745hx-rtx5060",
    brand: "Lenovo",
    series: "Legion Pro 5",
    sku: "LNV-LEGP5-R7-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 799990,
    oldPrice: 889990,
    discountPercent: 10,
    saving: 90000,
    monthlyPayment: 66666,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: false,
    isSale: false,
    rating: 4.8,
    reviewCount: 167,
    color: "Onyx Grey",
    weight: "2.5 кг",
    processor: "AMD Ryzen 7 8745HX",
    processorBrand: "AMD",
    gpu: "NVIDIA GeForce RTX 5060 8GB",
    gpuBrand: "NVIDIA",
    ram: "32 ГБ DDR5",
    storage: "1 ТБ NVMe SSD",
    display: "16\"",
    resolution: "2560×1600",
    refreshRate: "240 Гц",
    matrixType: "IPS",
    warranty: "1 год",
    os: "Windows 11 Home",
    battery: "99.9 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "360 × 264 × 22.4 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4 × 2, HDMI 2.1, RJ-45",
    shortDescription: "Legion Pro 5 с Ryzen 7 и 32 ГБ RAM для профессиональных задач",
    description: "Lenovo Legion Pro 5 с AMD Ryzen 7 8745HX и 32 ГБ — сбалансированный мощный игровой ноутбук.",
    advantages: ["AMD Ryzen 7 8745HX","32 ГБ DDR5","RTX 5060 8GB","240 Гц 2K","Thunderbolt 4 × 2","Wi-Fi 6E","99.9 Вт·ч","Legion AI Engine"],
    bgGradient: "linear-gradient(150deg,#F0EBF5,#E8DFF0)",
    svgColor1: "#4e1a6e",
    svgColor2: "#e4400f",
    images: [],
  },
  {
    id: 19,
    name: "Lenovo Legion 5 Intel Core i9-14900HX / 16GB / 1TB / RTX 5070",
    slug: "lenovo-legion-5-i9-14900hx-rtx5070",
    brand: "Lenovo",
    series: "Legion 5",
    sku: "LNV-LEG5-I9-001",
    categorySlug: "gaming",
    categoryName: "Игровые ноутбуки",
    price: 999990,
    oldPrice: 1099990,
    discountPercent: 9,
    saving: 100000,
    monthlyPayment: 83332,
    inStock: true,
    stockStatus: "in_stock",
    isNew: true,
    isHit: true,
    isSale: false,
    rating: 5.0,
    reviewCount: 78,
    color: "Titanium Grey",
    weight: "2.5 кг",
    processor: "Intel Core i9-14900HX",
    processorBrand: "Intel",
    gpu: "NVIDIA GeForce RTX 5070 8GB",
    gpuBrand: "NVIDIA",
    ram: "16 ГБ DDR5",
    storage: "1 ТБ NVMe SSD Gen4",
    display: "16\"",
    resolution: "2560×1600",
    refreshRate: "240 Гц",
    matrixType: "IPS",
    warranty: "2 года",
    os: "Windows 11 Home",
    battery: "99.9 Вт·ч",
    wifi: "Wi-Fi 6E",
    bluetooth: "Bluetooth 5.3",
    camera: "1080p FHD",
    dimensions: "360 × 264 × 22.4 мм",
    ports: "USB-A 3.2 × 3, USB-C Thunderbolt 4 × 2, HDMI 2.1, RJ-45, SD Card",
    shortDescription: "Топовый Legion 5 с Core i9 и RTX 5070 — для непримиримых геймеров",
    description: "Lenovo Legion 5 с Intel Core i9-14900HX и RTX 5070 — максимальная производительность в линейке Legion.",
    advantages: ["Intel Core i9-14900HX","RTX 5070 8GB GDDR7","240 Гц 2K QHD+","Thunderbolt 4 × 2","99.9 Вт·ч","Гарантия 2 года","Wi-Fi 6E","Legion AI Engine+"],
    bgGradient: "linear-gradient(150deg,#EBEAF9,#DDDCF5)",
    svgColor1: "#1a1a6e",
    svgColor2: "#e4400f",
    images: [],
  },
];

export const CATEGORIES = [
  { slug: "gaming", name: "Игровые ноутбуки", icon: "gamepad", count: 128, desc: "RTX 5060/5070/5080, высокочастотные дисплеи" },
  { slug: "office", name: "Для работы", icon: "briefcase", count: 96, desc: "Офисные и деловые ноутбуки" },
  { slug: "student", name: "Для учёбы", icon: "book", count: 64, desc: "Доступные ноутбуки для студентов" },
  { slug: "ultrabook", name: "Ультрабуки", icon: "zap", count: 52, desc: "Тонкие и лёгкие, до 1.5 кг" },
  { slug: "macbook", name: "MacBook", icon: "apple", count: 22, desc: "Apple MacBook Air и Pro" },
  { slug: "designer", name: "Для дизайнеров", icon: "palette", count: 31, desc: "OLED, цветоточные экраны, Quadro" },
  { slug: "dev", name: "Для разработчиков", icon: "code", count: 44, desc: "RAM 32+ ГБ, Linux ready" },
  { slug: "video", name: "Для видеомонтажа", icon: "film", count: 28, desc: "RTX, большой SSD, цветоточный дисплей" },
  { slug: "rtx", name: "Ноутбуки с RTX", icon: "cpu", count: 87, desc: "NVIDIA GeForce RTX 40/50 серии" },
  { slug: "oled", name: "Ноутбуки с OLED", icon: "monitor", count: 34, desc: "OLED-матрица для идеальной картинки" },
  { slug: "business", name: "Для бизнеса", icon: "target", count: 45, desc: "Корпоративные решения" },
  { slug: "accessories", name: "Аксессуары", icon: "package", count: 210, desc: "Мыши, сумки, коврики, хабы" },
];

export const BRANDS = [
  { name: "ASUS", slug: "asus" },
  { name: "Lenovo", slug: "lenovo" },
  { name: "HP", slug: "hp" },
  { name: "Acer", slug: "acer" },
  { name: "Dell", slug: "dell" },
  { name: "MSI", slug: "msi" },
  { name: "Apple", slug: "apple" },
  { name: "Gigabyte", slug: "gigabyte" },
  { name: "Huawei", slug: "huawei" },
  { name: "Honor", slug: "honor" },
];

export const REVIEWS = [
  { author: "Данияр Т.", initials: "ДТ", color: "linear-gradient(135deg,#FF5A1F,#FF8A50)", product: "ASUS ROG Strix G16", rating: 5, text: "Взял ROG Strix для стрима и монтажа — тянет всё без единой просадки. Доставили на следующий день, курьер сам всё распаковал и помог настроить.", source: "2GIS" },
  { author: "Айгерим К.", initials: "АК", color: "linear-gradient(135deg,#6b6b72,#3a3a40)", product: "Lenovo Legion Pro 5", rating: 5, text: "Оформила Legion Pro 5 в рассрочку без первого взноса — всё прошло онлайн за 10 минут. Ноутбук пришёл в идеальной упаковке, консультант помог с переносом данных.", source: "2GIS" },
  { author: "Руслан М.", initials: "РМ", color: "linear-gradient(135deg,#1AA35C,#2ECC71)", product: "HP Omen 16", rating: 5, text: "HP Omen 16 — лучший ноутбук, которым я владел. Экран потрясающий, батарея на удивление долго держит. OnePoint — рекомендую всем!", source: "2GIS" },
  { author: "Серик А.", initials: "СА", color: "linear-gradient(135deg,#3B82F6,#60A5FA)", product: "Lenovo IdeaPad Slim 3", rating: 5, text: "Брал ноутбук для дочери на учёбу. Отличный выбор за эти деньги! Быстро работает, красивый дизайн. Спасибо OnePoint за профессиональную консультацию.", source: "2GIS" },
  { author: "Малика Б.", initials: "МБ", color: "linear-gradient(135deg,#A855F7,#C084FC)", product: "ASUS TUF Gaming F16", rating: 5, text: "Долго выбирала первый игровой ноутбук — помогли подобрать TUF F16. Играю в сложные игры на максималках. Очень довольна покупкой!", source: "2GIS" },
  { author: "Болат И.", initials: "БИ", color: "linear-gradient(135deg,#EF4444,#F87171)", product: "HP OmniBook 5", rating: 5, text: "Ноутбук для командировок — OmniBook 5 идеален. Лёгкий, быстрый, заряда хватает на весь день. Оформление и доставка — супер.", source: "2GIS" },
];

export type Product = typeof PRODUCTS[number];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find(p => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string) {
  return PRODUCTS.filter(p => p.categorySlug === categorySlug);
}

export function getHitProducts() {
  return PRODUCTS.filter(p => p.isHit);
}

export function getNewProducts() {
  return PRODUCTS.filter(p => p.isNew);
}

export function getSaleProducts() {
  return PRODUCTS.filter(p => p.isSale);
}

export function formatPrice(price: number): string {
  return price.toLocaleString("ru-KZ") + " ₸";
}
