CREATE DATABASE IF NOT EXISTS onepoint_laptops CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE onepoint_laptops;

CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, login VARCHAR(80) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS brands (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, slug VARCHAR(120) NOT NULL UNIQUE, is_active TINYINT(1) NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS categories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, slug VARCHAR(150) NOT NULL UNIQUE, is_active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS products (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(500) NOT NULL, slug VARCHAR(500) NOT NULL UNIQUE, sku VARCHAR(100), brand_id INT UNSIGNED NULL, category_id INT UNSIGNED NULL,
  short_description TEXT, description TEXT, price DECIMAL(12,2) NOT NULL, old_price DECIMAL(12,2) NULL, monthly_payment DECIMAL(12,2) NULL,
  in_stock TINYINT(1) NOT NULL DEFAULT 1, is_new TINYINT(1) NOT NULL DEFAULT 0, is_hit TINYINT(1) NOT NULL DEFAULT 0, is_sale TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1,
  rating DECIMAL(2,1) NOT NULL DEFAULT 5.0, review_count INT NOT NULL DEFAULT 0, image_url VARCHAR(500), processor VARCHAR(200), gpu VARCHAR(200), ram VARCHAR(60), storage VARCHAR(100), display_size VARCHAR(60), resolution VARCHAR(60), refresh_rate VARCHAR(40), matrix_type VARCHAR(60), weight VARCHAR(40), color VARCHAR(80), os VARCHAR(100), warranty VARCHAR(100), battery VARCHAR(100), ports TEXT, wifi VARCHAR(100), bluetooth VARCHAR(60), camera VARCHAR(60), dimensions VARCHAR(100), advantages TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL, CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  INDEX idx_catalog (is_active, category_id, brand_id, price), INDEX idx_flags (is_hit, is_sale, is_new)
);
CREATE TABLE IF NOT EXISTS product_images (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  product_id INT UNSIGNED NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255) NULL,
  is_main TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_image_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  INDEX idx_product_images (product_id, is_main, sort_order)
);
CREATE TABLE IF NOT EXISTS reviews (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, product_id INT UNSIGNED NULL, author_name VARCHAR(160) NOT NULL, initials VARCHAR(10), rating TINYINT UNSIGNED NOT NULL DEFAULT 5, body TEXT NOT NULL, source VARCHAR(50) DEFAULT 'site', is_approved TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS promotions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT, badge VARCHAR(100), button_text VARCHAR(100), button_url VARCHAR(500), color VARCHAR(40) DEFAULT 'orange', is_active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, ends_at DATETIME NULL
);
CREATE TABLE IF NOT EXISTS leads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, type VARCHAR(50) DEFAULT 'request', product_id INT UNSIGNED NULL, name VARCHAR(160), phone VARCHAR(40), email VARCHAR(160), message TEXT, status ENUM('new','processing','done') DEFAULT 'new', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(100) PRIMARY KEY, `value` TEXT, label VARCHAR(150));
